<?php

return [
    'options' => [
        '*' => 'SUPER ADMIN (Akses Penuh)',
        'ticket.view' => 'View Tickets',
        'ticket.create' => 'Create Tickets',
        'ticket.update' => 'Update Tickets (Reply/Status)',
        'ticket.delete' => 'Delete Tickets',
        'ticket.change_sla' => 'Change Ticket SLA',
        'ticket.export' => 'Export Tickets',
        'dashboard.view' => 'View Dashboard Stats',
        'category.view' => 'View Categories',
        'category.manage' => 'Manage Categories',
        'location.view' => 'View Locations',
        'location.manage' => 'Manage Locations',
        'sla.view' => 'View SLAs',
        'sla.manage' => 'Manage SLAs',
        'master_lapor.view' => 'View Data Karyawan',
        'master_lapor.manage' => 'Manage Data Karyawan',
        'user.view' => 'View Users',
        'user.manage' => 'Manage Users',
    ],

    'labels' => [
        '*' => 'SUPER ADMIN',
        'ticket.view' => 'Lihat Tiket',
        'ticket.create' => 'Buat Tiket',
        'ticket.update' => 'Update Tiket',
        'ticket.delete' => 'Hapus Tiket',
        'ticket.change_sla' => 'Ubah SLA Tiket',
        'ticket.export' => 'Export Tiket',
        'dashboard.view' => 'Lihat Dashboard',
        'category.view' => 'Lihat Kategori',
        'category.manage' => 'Kelola Kategori',
        'location.view' => 'Lihat Lokasi',
        'location.manage' => 'Kelola Lokasi',
        'sla.view' => 'Lihat SLA',
        'sla.manage' => 'Kelola SLA',
        'master_lapor.view' => 'Lihat Data Karyawan',
        'master_lapor.manage' => 'Kelola Data Karyawan',
        'user.view' => 'Lihat Pengguna',
        'user.manage' => 'Kelola Pengguna',
    ],
];
